BarberShop/Controllers/BarberController.cs
using BarberShop.Models;
using BarberShop.Services;
using BarberShop.ViewModelBarber;
using Microsoft.AspNetCore.Mvc;

namespace BarberShop.Controllers
{
	public class BarberController : Controller
	{
		public IActionResult Index(int? id)
		{
           Barber barber = DataLayer.Instance.Users.OfType<Barber>().ToList().Find(u=>u.IDRandom == id);

            return View(barber);
		}
        public IActionResult SelectAction()
        {
            List<HairCutActions> actions = DataLayer.Instance.HairCutActions.ToList();
            return View(new VMSelectAction { HaircutOptionalActions = actions, Barber = (Barber)DataLayer.Instance.CurrUser, BarberID = DataLayer.Instance.CurrUser.ID });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SelectAction(VMSelectAction VM)
        {
            ActionPerBarber haircutActionsPerBarber = new ActionPerBarber();
            haircutActionsPerBarber.Action = DataLayer.Instance.HairCutActions.FirstOrDefault(g => g.ID == VM.HaircutActionID);

            if (haircutActionsPerBarber != null && VM != null)
            {
                haircutActionsPerBarber.Barber = DataLayer.Instance.Users.OfType<Barber>().ToList().FirstOrDefault(g => g.ID == VM.BarberID);
                haircutActionsPerBarber.ActionDuration = VM.ActionDuration;
                haircutActionsPerBarber.Price = VM.Price;
                haircutActionsPerBarber.PercentPerWork = VM.PercentFromTotalActions;
                haircutActionsPerBarber.Barber.Actions.Add(haircutActionsPerBarber);
                DataLayer.Instance.ActionPerBarber.Add(haircutActionsPerBarber);
                DataLayer.Instance.SaveChanges();

            }

            return RedirectToAction("Index", "home");

        }

        public IActionResult MyActions(int? id)
        {


            Barber barber = DataLayer.Instance.getBarbersAllIncludes.Find(b => b.IDRandom == id);

            List<ActionPerBarber> myActions = barber.Actions;


            return View(myActions);
        }

        //פונקצית הוספת תוכנית תאריכית
        public IActionResult addProgram(int? id)
        {
            if (id == null) return RedirectToAction("index", "home");
            User user = DataLayer.Instance.Users.ToList().Find(u => u.IDRandom == id);
            if (user == null) return RedirectToAction("index", "home");
            user.RND = 0;
            DataLayer.Instance.SaveChanges();
            DataLayer.Instance.CurrUser = user;
            VMSchedualProgram vMSchedual = new VMSchedualProgram
            {
                Barber = (Barber)user,
                BarberID = user.RND
            };
            return View(vMSchedual);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult addProgram(VMSchedualProgram VM)
        {
            new BarberService { VM = VM }.PlanProgram();
            DataLayer.Instance.SaveChanges();
            return RedirectToAction("Calender", new {id = VM.BarberID});

        }
		public IActionResult Calender(int? id)
        {
            Barber barber = DataLayer.Instance.getBarbersAllIncludes.Find(u=>u.IDRandom == id);
            return View(new VMCalander { Appointments = barber.Appointments});
        }
        
    }
}

BarberShop/Controllers/ManagerController.cs
using BarberShop.Models;
using BarberShop.ViewModelManager;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading;

namespace BarberShop.Controllers
{
    public class ManagerController : Controller
	{
		//פונקציה המוסיפה ספר
		public IActionResult AddBarber()
		{
            VMIsActiveBarbers VMUsers = new VMIsActiveBarbers(DataLayer.Instance.Users.ToList());
            return View(VMUsers);
		}
        public IActionResult CreateBarber(int? id)
        {
            if (id == null) return RedirectToAction("Index");

            List<User> users = DataLayer.Instance.Users.ToList();

            ClientUser client = users.OfType<ClientUser>().ToList().Find(User => User.ID == id);

            DataLayer.Instance.Database.ExecuteSqlCommand("UPDATE BarberShop.dbo.Users SET Discriminator = 'Barber' WHERE ID = {0}", id);

            DataLayer.Instance.SaveChanges();

            //VMIsActiveBarber vm = new VMIsActiveBarber(DataLayer.Data.Users.ToList());


            return View("index");
        }
        public IActionResult Barbers()
        {
            VMIsActiveBarbers VMBarbers = new VMIsActiveBarbers(DataLayer.Instance.Users.ToList());
            return View(VMBarbers);
        }
        public IActionResult ChangeActive(int? id)
        {
            //להביא רשימה של המשתמשים ולא רק הספרים
            //בשביל לבנות את המודל ולהחזיר אותו בVIEW
            //ובכך לחסוך פניה למסד נתונים
            List<User> barbers = DataLayer.Instance.Users.ToList();

            if(id != null)
            {
                Barber barber = (Barber)barbers.Find(b => b.ID == id);

                if (barber != null && barber is Barber) barber.Active = !barber.Active;

                DataLayer.Instance.SaveChanges();
            }

            return View("Barbers", new VMIsActiveBarbers(barbers));
        }

        //פונקציה המוסיפה פעולה ומציגה את כל הפעולות
        public IActionResult Actions(int? id)
        {
            List<HairCutActions> actions = DataLayer.Instance.HairCutActions.ToList();
            return View(new VMCreateHairCut {ActionList = actions });
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Actions(VMCreateHairCut VM)
        {
            DataLayer.Instance.HairCutActions.Add(VM.Action);
            VM.Action.SetImage = VM.File;
            DataLayer.Instance.SaveChanges();
            return RedirectToAction("Actions");
        }
        public IActionResult Index(int? id)
        {
            if (id == null)
            {
                DataLayer.Instance.CurrUser = new ClientUser { FirstName = "התחבר" };
                return RedirectToAction("Index", "Home");
            }
            User user = DataLayer.Instance.Users.FirstOrDefault(u => u.IDRandom == id);
            if (user != null)
                if (user is ManagerUser)
                {
                    DataLayer.Instance.CurrUser = user;
                    user.RND = 0;
                    DataLayer.Instance.SaveChanges();
                    return View();
                }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult ShowAllUsers()
        {
            List<User> users = DataLayer.Instance.Users.ToList();
            return View(users);

        }
    }
}

BarberShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BarberShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarberShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-route-id="@DataLayer.Instance.CurrUser.IDRandom" asp-area="" asp-controller="Home" asp-action="Login">@DataLayer.Instance.CurrUser.FullName</a>
                        </li>
                        @if (@DataLayer.Instance.CurrUser is ManagerUser)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-route-id="@DataLayer.Instance.CurrUser.IDRandom" asp-area="" asp-controller="Manager" asp-action="Index">מסך ניהול</a>
                            </li>  
                        }
                        @if (@DataLayer.Instance.CurrUser is Barber)
                        {
                             <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-id="@DataLayer.Instance.CurrUser.IDRandom" asp-controller="Barber" asp-action="Index">ספר</a>
                        </li>
                        }
                       
                        @if (@DataLayer.Instance.CurrUser.FirstName != "התחבר")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-route-id=" " asp-area="" asp-controller="Home" asp-action="Login">יציאה</a>
                            </li>
                        }
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BarberShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/addaction.js"></script>
	<script src="~/js/change.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>